### PR TITLE
Cleared Issue #19

### PR DESCRIPTION
**Pull request by oxi-git**
Attaching log for proof of work:
proof

### CODE REVIEW

**Comment by oxi-git** [comment]
Typo on commit messages, meant Issue #19

**Comment by n0toose** [comment]
Hey @Oxigen96, thanks for helping me out with this! I'll definitely give this a shot and rebase late, but do you happen here for the Hacktoberfest event by DigitalOcean? If that's the case, you may want to resubmit this PR in October.

**Comment by oxi-git** [comment]
Thanks for the answer. Hacktoberfest and my interest in python brought me here, I'll resubmit this in October! 🎃

**Comment by n0toose** [comment]
> Thanks for the answer. Hacktoberfest and my interest in python brought me here, I'll resubmit this in October! 🎃

Got ya, see you then!

Wouldn't want you to contribute to an open-source project and turn out to be disappointed like that :P

**Pull request closed without merging**
