### PR TITLE
Update intro screen

### LINKED ISSUE #8: Update intro screen
I initially started [TinyFlowerBeds](https://twitter.com/tinyflowerbeds) in order to better understand Python's useful (and silly) applications and how to create apps that will interact with social media. After I took a simple approach for it, I made an intro screen that shows the name of the project, a copyright notice for [the project's license](LICENSE) and **also added my name with a copyright sign**.

https://github.com/AlwaysLivid/TinyFlowerBeds/blob/ad525983d4a143db1f34802e38ea2460c55bab4d/src/bot.py#L18

I essentially abandoned the project, but I've revived it, because I noticed that it's a simple fun thing to work on and that others could learn some useful stuff by fiddling around with it (just as I did). When I started working on it, however, I did not expect anybody else to improve the thing that I did. There has been some interest revolving around it and there have been people that have contributed their own source code! According to the [GNU General Public License v3](LICENSE), the rights to the source code that they wrote belongs to them. I'm not the only copyright holder anymore!

So, here's what should change;
* The year should be updated from `2018-2019` to `2018-2020`.
* Change my alias (`AlwaysLivid`) to something that includes my name, as well as the `contributors`, as well as a link that lists all of the people that have contributed to the bot on GitHub.
* Make sure that the alignment remains intact. Feel free to make changes all over the string in order to maintain that.

### PR DESCRIPTION
**Pull request by Mrlinkwii**

### CODE REVIEW

**Comment by n0toose** [comment]
Hey @Mrlinkwii, thanks for your contribution!

Could you also fix the alignment of line 18?
https://github.com/AlwaysLivid/TinyFlowerBeds/blob/84645e0e289cd4029515a6a8735dc55cb6fa7c07/src/bot.py#L18

**Comment by n0toose** [comment]
Also, I was kind of hoping for a link that leads to `https://github.com/AlwaysLivid/TinyFlowerBeds/contributors`. Do you think that it'd be manageable to add that one instead, or is it too long in your opinion?

**Comment by Mrlinkwii** [comment]
> Also, I was kind of hoping for a link that leads to `https://github.com/AlwaysLivid/TinyFlowerBeds/contributors`. Do you think that it'd be manageable to add that one instead, or is it too long in your opinion?

no problem ,  ,ill do that in a few minutes

**Comment by n0toose** [comment]
Can you maintain the alignment (center)?

**Comment by Mrlinkwii** [comment]
is that that OK?

**Comment by n0toose** [comment]
That's better, but the alignment is still towards the left. Could you align it towards the center?

**Comment by n0toose** [comment]
No, I mean that this needs to be in the middle and ***not towards the edge***, just like this;

image

**Comment by n0toose** [comment]
Hey, uh, what text editor are you using? This doesn't seem to be going as well as I'd expect (I go by the spaces of a terminal environment, so I'd recommend vi, GitHub or nano).

P.S. Please squash your commits before pushing.

**Comment by Mrlinkwii** [comment]
ill try and get this to work , if i can ill reopen

**Pull request closed without merging**
