### PR TITLE
Added GItHub Actions workflow for pushing new commits to Heroku

### PR DESCRIPTION
**Pull request by rohan2734**
Please check the yml file.

### CODE REVIEW

**Comment by n0toose** [comment]
Looks good to me, I will merge this once another contributor fixes a few of their changes in order to prevent the bot from breaking! (Shouldn't take more than a day.)

Thank you for your contribution!

**Comment by rohan2734** [comment]
> Looks good to me, I will merge this once another contributor fixes a few of their changes in order to prevent the bot from breaking! (Shouldn't take more than a day.)
> 
> Thank you for your contribution!

great , thanks for the opportunity too.

**Comment by rohan2734** [comment]
@panos  hey can you merge the pull request?, you said everything is fine right?

**Comment by n0toose** [comment]
Yeah, I've just been really busy as of late and have not had the time to test it, I'm keeping that in the back of my head.

**Comment by rohan2734** [comment]
> Yeah, I've just been really busy as of late and have not had the time to test it, I'm keeping that in the back of my head.

so when exactly are you gonna merge it?.

**Comment by n0toose** [comment]
> so when exactly are you gonna merge it?.

Hey, I'll merge it as soon as I manage to ensure that this pull request is good enough quality-wise. If you're worried about your t-shirt, you'll still get it, the PR should be mature in less than a day.

**Comment by rohan2734** [comment]
> Hey, I'll merge it as soon as I manage to ensure that this pull request is good enough quality-wise. If you're worried about your t-shirt, you'll still get it, the PR should be mature in less than a day.

no i am not worried about my tshirt,  I am just worried about PR, anyway i stopped contributing more for hacktoberfest.

**Pull request merged**
